In [2]:
import numpy as np

# Tableau d'entiers:

In [4]:
np.array([1, 4, 2, 5, 3])

array([1, 2, 3, 3, 2, 1])

## Concaténation

In [ ]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y])

In [8]:
x = np.array([1, 2, 3])
grid = np.array([[9, 8, 7],
                 [6, 5, 4]])

np.vstack([x, grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

# Opérations sur les tableaux Numpy

In [10]:
def calcul_inverse(valeurs):
    output = np.empty(len(valeurs))
    for i in range(len(valeurs)):
        output[i] = 1.0 / valeurs[i]
    return output

values = np.random.randint(1, 10, size=5)
print(calcul_inverse(values))

tableau_large = np.random.randint(1, 100, size=1000000)


[0.33333333 0.33333333 0.33333333 0.5        0.2       ]


##### Ceci est une facilité des notebooks jupyter pour mesurer le temps d'exécution d'une instruction

In [12]:
%timeit calcul_inverse(tableau_large)

1.43 s ± 43 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [13]:
%timeit (1.0 / tableau_large)

2.16 ms ± 137 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


À chaque fois que vous vous trouvez en train d'utiliser une boucle pour effectuer une opération en Python, demandez-vous si cette opération ne peut pas s'accomplir grâce à Numpy sans boucle.

## Opérations Booléennes

In [15]:
x = np.random.rand(10,10)
x > 0.5

array([[ True, False,  True,  True, False,  True, False, False, False,
         True],
       [ True,  True,  True,  True, False,  True, False,  True, False,
        False],
       [ True,  True, False, False, False, False,  True,  True, False,
        False],
       [ True, False,  True, False,  True, False, False, False,  True,
        False],
       [False,  True, False, False, False, False,  True,  True,  True,
        False],
       [False, False,  True,  True, False,  True,  True, False,  True,
        False],
       [ True,  True, False, False, False, False, False, False, False,
         True],
       [False,  True, False, False,  True, False, False,  True,  True,
         True],
       [ True, False, False,  True,  True,  True, False,  True, False,
        False],
       [False, False, False,  True, False, False, False, False, False,
         True]])

In [17]:
np.where(x>0.5)

(array([0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4,
        4, 5, 5, 5, 5, 5, 6, 6, 6, 7, 7, 7, 7, 7, 8, 8, 8, 8, 8, 9, 9],
       dtype=int64),
 array([0, 2, 3, 5, 9, 0, 1, 2, 3, 5, 7, 0, 1, 6, 7, 0, 2, 4, 8, 1, 6, 7,
        8, 2, 3, 5, 6, 8, 0, 1, 9, 1, 4, 7, 8, 9, 0, 3, 4, 5, 7, 3, 9],
       dtype=int64))

## Agrégation

In [20]:
L = np.random.random(100)
print(f"somme numpy : {np.sum(L)}")
%timeit sum(tableau_large)
%timeit np.sum(tableau_large)

somme numpy : 48.388139373247235
49.1 ms ± 492 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
311 µs ± 2.41 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


#### Notez la syntax variable.fonction au lieu de np.fonction(variable). Les deux sont possibles si
#### la variable est un tableau Numpy.

In [22]:
M = np.random.random((3, 4))
print(M)
print("La somme de tous les éléments de M: ", M.sum())
print("Les sommes des colonnes de M: ", M.sum(axis=0))

[[0.21909457 0.77338961 0.83393118 0.05827466]
 [0.55305607 0.63232784 0.34007961 0.24588367]
 [0.33073403 0.72344769 0.77285742 0.36823415]]
La somme de tous les éléments de M:  5.851310502181189
Les sommes des colonnes de M:  [1.10288467 2.12916514 1.94686821 0.67239248]


Parmi les nombreuses fonctions disponibles, notons :
-  np.std  pour calculer l'écart type
-  np.argmin  pour trouver l'index de l'élément minimum
-  np.percentile  pour calculer des statistiques sur les éléments.